ROOT=../..

CC= gcc
CFLAGS= -g -Wall -Wextra -std=c99 -I$(ROOT)/include
LDFLAGS= -std=c99 -L$(ROOT)/lib -L/usr/lib/x86_64-linux-gnu/ -lbcl -lfftw3 -lm

OBJ= mm.o main.o mm_dil.o mm_ero.o mm_open.o mm_close.o mm_substract

all: main mm_dil mm_ero mm_open mm_close mm_substract

main: main.o mm.o
	$(CC) main.o mm.o $(LDFLAGS) -o $@

mm_dil: mm_dil.o mm.o
	$(CC) mm_dil.o mm.o $(LDFLAGS) -o $@

mm_ero: mm_ero.o mm.o
	$(CC) mm_ero.o mm.o $(LDFLAGS) -o $@

mm_open: mm_open.o mm.o
	$(CC) mm_open.o mm.o $(LDFLAGS) -o $@

mm_close: mm_close.o mm.o
	$(CC) mm_close.o mm.o $(LDFLAGS) -o $@

mm_substract: mm_substract.o
	$(CC) mm_substract.o $(LDFLAGS) -o $@

mm.o: mm.c mm.h
main.o: main.c 
mm_dil.o: mm_dil.c
mm_ero.o: mm_ero.c
mm_open.o: mm_open.c
mm_close.o: mm_close.c
mm_substract.o: mm_substract.c

install : all
	cp main mm_dil mm_ero mm_open mm_close mm_substract $(ROOT)/bin/

clean :
	rm -f $(OBJ) main mm_dil mm_ero mm_open mm_close mm_substract
	rm -f *~


